### ISSUE TITLE
How use to do ssh dynamic port forwarding?

### ISSUE THREAD

**Issue by chenfeicqq** [sshtools/j2ssh-maverick#1]
I need use ssh dynamic port forwarding, this library can do it?

I see it support "Dynamic	SOCKS forwarding" feture in this page https://www.sshtools.com/en/products/j2ssh

**Comment by jamiewalters** [comment]
I noticed there is perhaps a bug in SSHConnector; Ssh2Context ssh2Context is never initialized so the connector always returns a NPE.

**Comment by ludup** [comment]
Seems there were several issues. I've committed fixes to github repository and released a new binary on sf.net.

**Comment by biggenius** [comment]
I am also looking for dynamic port forwarding.

**Comment by ludup** [comment]
I've now released 1.5.2 which includes Dynamic Port Forwarding.

The instructions are the same as our commercial API here:
https://javassh.zendesk.com/entries/76782015-Using-Dynamic-Port-Forwarding

**Comment by chenfeicqq** [comment]
3Q so much!
