### ISSUE TITLE
ScpConnect example not work

### ISSUE THREAD

**Issue by bibitoo** [sshtools/j2ssh-maverick#16]
When input password, the process just waiting.
Server and password is following:

Hostname: 66.42.44.175
Username [Enter for bibi]: root
Connecting to 66.42.44.175
The host |1|lYaziWXZ7wM6fIo0kD7lERvviCg=|W46arhY3ppGAaePPR3suy6WWFic= is currently unknown to the system
The MD5 host key (ssh-rsa) fingerprint is: b5:b7:83:49:50:97:26:85:e1:9e:45:e7:65:18:09:72
The SHA1 host key (ssh-rsa) fingerprint is: 41:fb:72:30:24:84:6e:5b:0a:17:82:01:29:f8:14:74:53:47:81:d0
The SHA256 host key (ssh-rsa) fingerprint is: fe:3e:6f:90:28:8b:7c:b9:3e:2b:76:96:11:03:90:21:28:b6:63:5b:7f:52:44:ef:6d:dd:d7:1e:73:f5:6f:a2
Do you want to allow this host key? [Yes|No|Always]: yes
Password: u9J=az)c2-7#mK]K

**Comment by ludup** [comment]
You should post a full set of debug logs and the actual code you are running. There could be 101 reasons for this.

**Comment by bibitoo** [comment]
The code is ScpConnect.java on master, I did not change anything.And there is no other log. The server and username/password is here, you may run it for a test.

**Comment by bibitoo** [comment]
My server has been remove. Stop test this.
