### ISSUE TITLE
Cd method of SFTP Client not working

### ISSUE THREAD

**Issue by RevathiPraba** [sshtools/j2ssh-maverick#2]
Team,

I am using maverick-all 1.4.39 in my application to do SFTP with remote server. I logged in as root. My  default dirctory is root.

Issue 1: When I tried to cd(".."), it return default dirctory. It shoud be return \\.
Issue2:  I called cdup() method instead of cd(".."). It returned \ . Then I did ls(\\). It return nothing.

Why nothing worked for \ . I want to go to my home dirctory and get files under home. Please help me to achieve this.

Thank you very much in advance.

Thanks & Regards
Revathi Praba

**Comment by ludup** [comment]
Please open a ticket at http://support.sshtools.com this issue is not related to the open source version.

**Comment by RevathiPraba** [comment]
Thank you for your reply.
