### ISSUE TITLE
Memory leaks when ciclic connecting to ssh serwer for local forwards

### ISSUE THREAD

**Issue by stvbox** [sshtools/j2ssh-maverick#3]
Please tell me how to realize the establishment and disconnection of a method call. My attempts to realize such a lead to memory leaks.

**Comment by ludup** [comment]
I don't understand the issue. However for every SshClient you connect, you must ensure that you call disconnect to release resources once you have finished using it. Not doing so may lead to sockets being left open.

If you can provide more specific details I'd be happy to comment on it further.

**Comment by ludup** [comment]
No response

**Comment by stvbox** [comment]
Thank you for this library - its work excelent.
I was misled - lazy garbage collector.
