### ISSUE TITLE
Support for PuTTY RSA aes256-cbc Algorithm

### ISSUE THREAD

**Issue by MitchTalmadge** [sshtools/j2ssh-maverick#4]
Hey, amazing library! I'm having trouble with RSA authentication though. I have tried two different RSA keys, both generated by the PuTTYGen tool.

The error I get when using the rsa.ppk file is as follows:

```
java.io.IOException: The PuTTY key could not be read! aes256-cbc is not supported [Unknown cause]
	at com.sshtools.publickey.PuTTYPrivateKeyFile.toKeyPair(PuTTYPrivateKeyFile.java:335)
```

Additionally (I don't know if this is related), the error I get when using the rsa file generated by PuTTYGen's OpenSSH Converter is as follows: (It's very vague.. I don't even know what the problem is)

```
com.sshtools.ssh.SshIOException
	at com.sshtools.publickey.PEMReader.decryptPayload(PEMReader.java:206)
	at com.sshtools.publickey.OpenSSHPrivateKeyFile.toKeyPair(OpenSSHPrivateKeyFile.java:86)
```

I am certain the supplied password is correct. Am I doing something wrong or is this something the library does not have support for?

Thanks

**Comment by MitchTalmadge** [comment]
I see now that aes256-cbc was deprecated. What's the reason behind this?

**Comment by ludup** [comment]
CBC ciphers are not considered secure due to publicised vulnerabilities. However there is no way around this issue other than to enable aes256-cbc for the private key operation. I will need to make a change, should be trivial in order to support it.

**Comment by ludup** [comment]
I've just committed a change to develop to fix this. Since the ciphers were still in the classpath these are used directly instead of through the ComponentManager, which was always subject to changes in configuration by user.

**Comment by hjerting** [comment]
I still can't seem to use my AES-256-CBC key with puttygen. Is this issue not resolved?
