### ISSUE TITLE
NullPointerException in ForwardingClient.SocketListener#run

### ISSUE THREAD

**Issue by Sumetzberger** [sshtools/j2ssh-maverick#7]
The 6th line in the method "run" in the class "com.sshtools.net.ForwardingClient.SocketListener" is `final Socket socket = server.accept();`. The variable "server" can be null at this point which results in a NullPointerException. I recommend to change this code to `ServerSocket server = this.server; if (server == null) {break;} final Socket socket = server.accept();`.
I'm sorry I can't provide you a code snippet to reproduce this exception (because I can't reproduce it myself).

**Comment by ludup** [comment]
Thanks.

I think its safer to set server = null at the end of the run method. Setting it in stop could still mean there is a slight chance its not null in an if but null when it comes to calling accept.

Committed fix to develop. Will release shortly.
