### ISSUE TITLE
Exception appears when trying to ping using the following method 

### ISSUE THREAD

**Issue by jocnud** [sshtools/j2ssh-maverick#8]
08:16:38,991 ERROR [stderr] (172.23.38.2:22[0]) Dec 5, 2016 8:16:38 AM [Plug-in standard error]: java.lang.NullPointerException
08:16:38,992 ERROR [stderr] (172.23.38.2:22[0]) Dec 5, 2016 8:16:38 AM [Plug-in standard error]:        at com.sshtools.ssh2.Ssh2Client.isAuthenticated(Ssh2Client.java:382)

@Override
	protected boolean ping() {
		System.out.println("Session " + session);
		return !session.isClosed() && sck.isAuthenticated() && sck.isConnected();
}

**Comment by ludup** [comment]
Need more of the log and more of your code.

**Comment by ludup** [comment]
Non responsive.
